%%{init: {'theme': 'neutral', 'fontFamily': 'Noto Sans'}}%%

classDiagram
    direction LR
    Site "1" -- "0..n" ProvidedService
    ProvidedService "1" -- "1..n" ProvidedPort
    class Site {
        name
        &lt;options&gt;
    }
   class ProvidedService {
        name
        target
        &lt;options&gt;
    }
    class ProvidedPort {
        port
        name
        protocol
        targetPort
        &lt;options&gt;
    }
