classes: {
  notion: {
    style: {
      stroke-width: 1
      fill: "#eee"
      bold: false
      italic: true
    }
  }

  neutral: {
    style: {
      stroke-width: 1
      fill: "#eee"
      font-size: 16
    }
  }
}

direction: right
