direction: right

Site E1 -- Site C1
Site E2 -- Site C1
Site C1 -- Site C2
Site C2 -- Site E3
Site C2 -- Site E4

Site E5 -- Site C3
Site E6 -- Site C3
Site C3 -- Site C4
Site C4 -- Site E7
Site C4 -- Site E8

# Site C1 -- Site C4
# Site C2 -- Site C3
