direction: right

Kubernetes cluster.Site 1 -- Docker instance.Site 1 -- Linux host.Site 1
Kubernetes cluster.Site 2 -- Docker instance.Site 2 -- Linux host.Site 2
Kubernetes cluster.Site 3 -- Docker instance.Site 3 -- Linux host.Site 3
