...@common

Canvas: {
  Platform 1: {
    Namespace: {
      Site
    }
  }

  Platform 2: {
    Namespace: {
      Site
    }
  }

  Platform 1.Namespace.Site -- Platform 2.Namespace.Site
}

Canvas.class: canvas
