...@common

direction: down

Canvas: {
  Platform: {
    Namespace 1: {
      Site: {
        W1
        W2
      }
    }

    Namespace 2: {
      Site: {
        W1
        W2
      }
    }

    Namespace 3: {
      Site: {
        style.opacity: 0
        W1
        W2
      }
    }
  }
}

Canvas.class: canvas