...@common

Frontend 1 -- Listener 1 -- Routing key -- Connector 1 -- Backend 1
Frontend 2 -- Listener 2 -- Routing key -- Connector 2 -- Backend 2

Routing key.label: "\"backend\""

Frontend*.class: notion
Backend*.class: notion
