...@common

Site 1.Client -> Site 1.Listener -- Routing key -- Site 2.Connector -> Site 2.Server

Routing key.class: notion
Site 1.Client.style.fill: white
Site 2.Server.style.fill: white
Site*.class: neutral
