%%{init: {'theme': 'neutral', 'fontFamily': 'Noto Sans'}}%%

classDiagram
    direction TB
    site "1" -- "0..n" `ingress-binding`
    site "1" -- "0..n" `egress-binding`
    class site {
        name
        &lt;options&gt;
    }
    class `egress-binding` {
        routing-key
        hostname
        port
        &lt;options&gt;
    }
    class `ingress-binding` {
        routing-key
        hostname
        port
        &lt;options&gt;
    }
