%%{init: {'theme': 'neutral', 'fontFamily': 'Noto Sans'}}%%

classDiagram
    direction TB
    site "1" -- "0..n" listener
    site "1" -- "0..n" connector
    class site {
        name
        ingress
        &lt;settings&gt;
        init()
        delete()
    }
    class listener {
        routing-key
        hostname
        port
        &lt;settings&gt;
        create()
        delete()
    }
    class connector {
        routing-key
        selector
        &lt;settings&gt;
        create()
        delete()
    }
