%%{init: {'theme': 'neutral', 'fontFamily': 'Noto Sans'}}%%

classDiagram
    direction TB
    Site "1" -- "0..n" Link
    Site "1" -- "0..n" Token
    Site "1" -- "0..n" ProvidedService
    Site "1" -- "0..n" RequiredService
    ProvidedService "1" -- "1..n" ProvidedPort
    RequiredService "1" -- "1..n" RequiredPort
    class Site {
        name
        &lt;options&gt;
    }
    class Link {
        name
        secret
        &lt;options&gt;
    }
    class Token {
        name
        secret
        &lt;options&gt;
    }
    class ProvidedService {
        name
        target
        &lt;options&gt;
    }
    class ProvidedPort {
        port
        name
        protocol
        targetPort
        &lt;options&gt;
    }
    class RequiredService {
        name
        &lt;options&gt;
    }
    class RequiredPort {
        port
        name
        protocol
        &lt;options&gt;
    }
