name: AttachedConnectorBinding
platforms: [Kubernetes]
related_resources: [attached-connector]
links: [skupper/attached-connectors]
description: |-
  An attached connector binding is a binding to an attached connector in a peer namespace that allows you to 
  bring a workload into your existing VAN without creating a separate site or establishing inter-site links.
  The name of this resource must be the same as that of the associated AttachedConnector resource in the peer 
  namespace.
metadata:
  include_properties: [metadata/*]
  properties:
    - name: name
      description: |
        @description@

        The name must be the same as that of the associated
        AttachedConnector resource in the connector namespace.
  description: |-
    An attached connector binding is a binding to an attached connector in a peer namespace that allows you to 
    bring a workload into your existing VAN without creating a separate site or establishing inter-site links.
    The name of this resource must be the same as that of the associated AttachedConnector resource in the peer 
    namespace.
spec:
  include_properties: [connector/spec/routingKey, 
        connector/spec/exposePodsByName, settings]
  properties:
    - name: connectorNamespace
      description: |-
        The name of the namespace where the associated AttachedConnector is located.
status:
  include_properties: [status/*, connector/status/hasMatchingListener]
  exclude_properties: [status/message]
